/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajitminerals;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;

/**
 *
 * @author neer
 */
public class weight_slip extends javax.swing.JFrame {

    /**
     * Creates new form weight_slip
     */
    public weight_slip() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setPreferredSize(dim);
        System.out.println(dim);
        tf_rst.setText(""+dim);
        weight_slip_panel.setBackground(Color.white);
        printstart();
        InputStream is = getClass().getResourceAsStream("/DOTMATRI.ttf");
        
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, is).deriveFont(Font.PLAIN,48);
            lb_add1.setFont(font);
        } catch (FontFormatException ex) {
            Logger.getLogger(weight_slip.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(weight_slip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void printstart(){
        Date date = new Date(); 
        SimpleDateFormat formatter = new SimpleDateFormat("EEE dd/MM/yyyy");
        SimpleDateFormat time= new SimpleDateFormat("HH:mm a");
        String strDate= formatter.format(date);
        String strTime= time.format(date);
        tf_grossdate.setText(strDate);
        tf_taredate.setText(strDate);
        tf_grosstime.setText(strTime);
        tf_taretime.setText(strTime);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        weight_slip_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_add1 = new javax.swing.JLabel();
        lb_add2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_rst = new javax.swing.JLabel();
        lb_partyname = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lb_material = new javax.swing.JLabel();
        lb_vehicle = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_gross = new javax.swing.JLabel();
        lb_tare = new javax.swing.JLabel();
        lb_net = new javax.swing.JLabel();
        lb_grossdate = new javax.swing.JLabel();
        lb_taredate = new javax.swing.JLabel();
        lb_taretime = new javax.swing.JLabel();
        lb_grosstime = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        tf_rst = new javax.swing.JTextField();
        tf_partyname = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        tf_vehicle = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        tf_material = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        tf_gross = new javax.swing.JTextField();
        tf_tare = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        tf_grossdate = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        tf_grosstime = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        tf_taredate = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        tf_taretime = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        cb_address = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1600, 800));
        setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));

        jLabel2.setFont(new java.awt.Font("Dot Matrix", 0, 36)); // NOI18N
        jLabel2.setText("CHOUDHARY FAIR SCALE");

        lb_add1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lb_add1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_add1.setText("OPP. J. K. CEMENT FACTORY");

        lb_add2.setFont(new java.awt.Font("Dot Matrix", 0, 24)); // NOI18N
        lb_add2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_add2.setText("GOTAN, DIST. NAGAUR (RAJ.)");

        jLabel5.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel5.setText("RST No      :");

        jLabel6.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel6.setText("PARTY NAME  :");

        lb_rst.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_rst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_rst.setText(" ");

        lb_partyname.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_partyname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_partyname.setText(" ");

        jLabel15.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel15.setText("VEHICLE No   :");

        jLabel16.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel16.setText("MATERIALS    :");

        lb_material.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_material.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_material.setText(" ");

        lb_vehicle.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_vehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_vehicle.setText(" ");

        jLabel19.setFont(new java.awt.Font("Dot Matrix", 0, 8)); // NOI18N
        jLabel19.setText("***********************************************************************************************************************************************************");

        jLabel7.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel7.setText("GROSS    ");

        jLabel8.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel8.setText("TARE");

        jLabel9.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel9.setText("NET");

        jLabel10.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel10.setText(":");

        jLabel11.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel11.setText(":");

        jLabel12.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel12.setText(":");

        lb_gross.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_gross.setText("0 KG");

        lb_tare.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_tare.setText("0 KG");

        lb_net.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_net.setText("0 KG");

        lb_grossdate.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_grossdate.setText("DATE :");

        lb_taredate.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_taredate.setText("DATE :");

        lb_taretime.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_taretime.setText("TIME :");

        lb_grosstime.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        lb_grosstime.setText("TIME :");

        jLabel27.setFont(new java.awt.Font("Dot Matrix", 0, 8)); // NOI18N
        jLabel27.setText("***********************************************************************************************************************************************************");

        jLabel28.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel28.setText("CHARGES");

        jLabel29.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel29.setText(":");

        jLabel30.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel30.setText("Rs. 200");

        jLabel31.setFont(new java.awt.Font("Dot Matrix", 0, 8)); // NOI18N
        jLabel31.setText("***********************************************************************************************************************************************************");

        jLabel32.setFont(new java.awt.Font("Dot Matrix", 0, 16)); // NOI18N
        jLabel32.setText("OPERATOR SIGNATURE : ");

        jLabel33.setFont(new java.awt.Font("Dot Matrix", 0, 8)); // NOI18N
        jLabel33.setText("***********************************************************************************************************************************************************");

        javax.swing.GroupLayout weight_slip_panelLayout = new javax.swing.GroupLayout(weight_slip_panel);
        weight_slip_panel.setLayout(weight_slip_panelLayout);
        weight_slip_panelLayout.setHorizontalGroup(
            weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weight_slip_panelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(weight_slip_panelLayout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(weight_slip_panelLayout.createSequentialGroup()
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_tare, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_gross, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_net, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(131, 131, 131)
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_grossdate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_taredate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_grosstime, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_taretime, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weight_slip_panelLayout.createSequentialGroup()
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(weight_slip_panelLayout.createSequentialGroup()
                                .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lb_partyname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_rst, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGap(55, 55, 55)
                                .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lb_vehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(lb_material, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, weight_slip_panelLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(531, 531, 531))
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(117, 117, 117))))
            .addGroup(weight_slip_panelLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_add1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_add2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        weight_slip_panelLayout.setVerticalGroup(
            weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weight_slip_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lb_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_add2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(weight_slip_panelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6))
                        .addGroup(weight_slip_panelLayout.createSequentialGroup()
                            .addComponent(lb_rst)
                            .addGap(18, 18, 18)
                            .addComponent(lb_partyname)))
                    .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(weight_slip_panelLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel16))
                        .addGroup(weight_slip_panelLayout.createSequentialGroup()
                            .addComponent(lb_vehicle)
                            .addGap(18, 18, 18)
                            .addComponent(lb_material))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(weight_slip_panelLayout.createSequentialGroup()
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)))
                    .addGroup(weight_slip_panelLayout.createSequentialGroup()
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_gross)
                            .addComponent(lb_grossdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_tare)
                            .addComponent(lb_taredate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_net))
                    .addGroup(weight_slip_panelLayout.createSequentialGroup()
                        .addComponent(lb_grosstime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_taretime)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(weight_slip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Weight Slip");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(weight_slip_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(weight_slip_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel34.setText("INPUT CONTROL");

        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel35.setText("RST NO.                   :");

        tf_rst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_rstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_rstFocusLost(evt);
            }
        });

        tf_partyname.setText("AJIT MINERALS");
        tf_partyname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_partynameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_partynameFocusLost(evt);
            }
        });

        jLabel36.setText("PARTY NAME             :");

        tf_vehicle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_vehicleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_vehicleFocusLost(evt);
            }
        });

        jLabel37.setText("VEHICLE No.              :");

        tf_material.setText("LIME");
        tf_material.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_materialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_materialFocusLost(evt);
            }
        });

        jLabel38.setText("MATERIALS               :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_material, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_partyname, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_rst, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tf_rst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(tf_partyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(tf_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(tf_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel39.setText("GROSS                     :");

        tf_gross.setText("0");
        tf_gross.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_grossFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_grossFocusLost(evt);
            }
        });

        tf_tare.setText("0");
        tf_tare.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_tareFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_tareFocusLost(evt);
            }
        });

        jLabel40.setText("TARE                       :");

        tf_grossdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_grossdateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_grossdateFocusLost(evt);
            }
        });

        jLabel41.setText("GROSS DATE            :");

        tf_grosstime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_grosstimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_grosstimeFocusLost(evt);
            }
        });

        jLabel42.setText("GROSS TIME             :");

        tf_taredate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_taredateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_taredateFocusLost(evt);
            }
        });

        jLabel43.setText("TARE DATE               :");

        tf_taretime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_taretimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_taretimeFocusLost(evt);
            }
        });

        jLabel44.setText("TARE TIME               :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_taretime, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_taredate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_grosstime, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_grossdate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_tare, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_gross, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(tf_gross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(tf_tare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(tf_grossdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(tf_grosstime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(tf_taredate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(tf_taretime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel45.setText("ADDRESS                 :");

        cb_address.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GOTAN", "PUNDLU", "KHIMSAR" }));
        cb_address.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_addressItemStateChanged(evt);
            }
        });

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel45)
                        .addGap(55, 55, 55)
                        .addComponent(cb_address, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(cb_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(156, 156, 156))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void tf_rstFocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        lb_rst.setText(tf_rst.getText());
    }                                

    private void tf_partynameFocusLost(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
        lb_partyname.setText(tf_partyname.getText());
    }                                      

    private void tf_vehicleFocusLost(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
        lb_vehicle.setText(tf_vehicle.getText());
    }                                    

    private void tf_materialFocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        lb_material.setText(tf_material.getText());
    }                                     

    private void tf_grossFocusLost(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
        lb_gross.setText(tf_gross.getText()+" KG");
    }                                  

    private void tf_tareFocusLost(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
        lb_tare.setText(tf_tare.getText()+" KG");
        int gross=Integer.parseInt(tf_gross.getText());
        int tare=Integer.parseInt(tf_tare.getText());
        lb_net.setText((gross-tare)+" KG");
    }                                 

    private void tf_grossdateFocusLost(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
        lb_grossdate.setText("DATE : "+tf_grossdate.getText());
    }                                      

    private void tf_grosstimeFocusLost(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
        lb_grosstime.setText("TIME : "+tf_grosstime.getText());
    }                                      

    private void tf_taredateFocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        lb_taredate.setText("DATE : "+tf_taredate.getText());
    }                                     

    private void tf_taretimeFocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        lb_taretime.setText("TIME :"+tf_taretime.getText());
    }                                     

    private void tf_rstFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
        tf_rst.selectAll();
    }                                  

    private void tf_partynameFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
        tf_partyname.selectAll();
    }                                        

    private void tf_vehicleFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
        tf_vehicle.selectAll();
    }                                      

    private void tf_materialFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        tf_material.selectAll();
    }                                       

    private void tf_grossFocusGained(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
        tf_gross.selectAll();
    }                                    

    private void tf_tareFocusGained(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
        tf_tare.selectAll();
    }                                   

    private void tf_grossdateFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
        tf_grossdate.selectAll();
    }                                        

    private void tf_grosstimeFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
        tf_grosstime.selectAll();
    }                                        

    private void tf_taredateFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        tf_taredate.selectAll();
    }                                       

    private void tf_taretimeFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        tf_taretime.selectAll();
    }                                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        /*String filename=tf_rst.getText();
        Document document = new Document();
        try{
            PdfWriter writer=PdfWriter.getInstance((com.itextpdf.text.Document) document,new FileOutputStream("C:\\Users\\neera\\OneDrive\\Desktop\\ajitminerals\\test1.pdf"));
            document.open();
            PdfContentByte contentByte=writer.getDirectContent();
            PdfTemplate template = contentByte.createTemplate(500,500);
            Graphics2D g2 = template.createGraphics(500,500);
            weight_slip_panel.print(g2);
            contentByte.addTemplate(template,30,300);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        finally{
            if(document.isOpen()){
                document.close();
            }
        }*/
        printInvoice(weight_slip_panel);
    }                                        

    private void cb_addressItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        // TODO add your handling code here:
        if(cb_address.getSelectedItem()=="GOTAN"){
            lb_add1.setText("OPP. J. K. CEMENT FACTORY");
            lb_add2.setText("GOTAN, DIST. NAGAUR (RAJ.)");
        }
        else if(cb_address.getSelectedItem()=="PUNDLU"){
            lb_add1.setText("BITTAN KHAWASPURA ROAD");
            lb_add2.setText("PUNDLU, DIST. NAGAUR (RAJ.)");
        }
        else if(cb_address.getSelectedItem()=="KHIMSAR"){
            lb_add1.setText("N.H.-65, MANAKPUR");
            lb_add2.setText("KHIMSAR, DIST. NAGAUR (RAJ.)");            
        }

    }                                           

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        cb_address.setSelectedItem(0);
        tf_rst.setText("");
        lb_rst.setText(" ");
        tf_partyname.setText("AJIT MINERALS");
        lb_partyname.setText(" ");
        tf_vehicle.setText("");
        lb_vehicle.setText(" ");
        tf_material.setText("LIME");
        lb_material.setText(" ");
        tf_gross.setText("0");
        lb_gross.setText("0 KG");
        tf_tare.setText("0");
        lb_tare.setText("0 KG");
        lb_net.setText("0 KG");
        lb_grossdate.setText(" ");
        lb_grosstime.setText(" ");
        lb_taredate.setText(" ");
        lb_taretime.setText(" ");
        printstart();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(weight_slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(weight_slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(weight_slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(weight_slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new weight_slip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cb_address;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lb_add1;
    private javax.swing.JLabel lb_add2;
    private javax.swing.JLabel lb_gross;
    private javax.swing.JLabel lb_grossdate;
    private javax.swing.JLabel lb_grosstime;
    private javax.swing.JLabel lb_material;
    private javax.swing.JLabel lb_net;
    private javax.swing.JLabel lb_partyname;
    private javax.swing.JLabel lb_rst;
    private javax.swing.JLabel lb_tare;
    private javax.swing.JLabel lb_taredate;
    private javax.swing.JLabel lb_taretime;
    private javax.swing.JLabel lb_vehicle;
    private javax.swing.JTextField tf_gross;
    private javax.swing.JTextField tf_grossdate;
    private javax.swing.JTextField tf_grosstime;
    private javax.swing.JTextField tf_material;
    private javax.swing.JTextField tf_partyname;
    private javax.swing.JTextField tf_rst;
    private javax.swing.JTextField tf_tare;
    private javax.swing.JTextField tf_taredate;
    private javax.swing.JTextField tf_taretime;
    private javax.swing.JTextField tf_vehicle;
    private javax.swing.JPanel weight_slip_panel;
    // End of variables declaration                   
private void printInvoice(JPanel panel){
        PrinterJob printerJob=PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Invoice");
        printerJob.setPrintable(new Printable(){
            @Override
            public int print(Graphics grphcs, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if(pageIndex>0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D=(Graphics2D)grphcs;
                graphics2D.translate(pageFormat.getImageableX(),pageFormat.getImageableY());
                graphics2D.scale(0.67,0.75);
                panel.paintComponents(grphcs);
                
                
                return Printable.PAGE_EXISTS;
                
            }
            
        });
        boolean returningResult=printerJob.printDialog();
        if(returningResult){
            try{
                printerJob.print();
            }catch(PrinterException printerException){
                JOptionPane.showMessageDialog(this,"Print Error : "+printerException.getMessage());
            }
        }
    }
}
